swagger: "2.0"

info:
  version: 1.0.0
  title: kubeResource
  description: Manage Third Party Resources from k8s

schemes:
  - https
host: kubernetes.default.svc

paths:
  /apis/{fqdn}/v1/{resource}:
    get:
      summary: Get resources
      description: Returns a list of resources of kind 
      responses:
        200:
          description: A list of resources
          schema:
            items:
              type: array
              items: 
                type: object
      parameters:
        - name: watch
          uniqueItems: true
          type: boolean
          description: Watch for changes to the described resources and return them as a stream
            of add, update, and remove notifications. Specify resourceVersion.
          in: query
        - name: resource
          in: path
          required: true
          description: The Resource's name
          type: string
        - name: fqdn
          in: path
          required: true
          description: The Resource's name
          type: string
  /apis/{fqdn}/v1/watch/{resource}:
    get:
      summary: Watch Resources
      description: Listen to events about Resources
      responses:
        200:
          description: A stream of events
          schema:
            type: object
      parameters:
        - name: resource
          in: path
          required: true
          description: The Resource's name
          type: string
        - name: fqdn
          in: path
          required: true
          description: The Resource's name
          type: string
  /apis/{fqdn}/v1/namespaces/{namespace}/{resource}/{name}:
    get:
      summary: Gets a specific Resource
      description: Returns a specific Resource in a namespace
      parameters:
        - name: namespace
          in: path
          required: true
          description: The Resource's namespace
          type: string
        - name: name
          in: path
          required: true
          description: The Resource's name
          type: string
        - name: resource
          in: path
          required: true
          description: The Resource's name
          type: string
        - name: fqdn
          in: path
          required: true
          description: The Resource's name
          type: string
      responses:
        200:
          description: A single Resource
          schema:
            type: object 