swagger: "2.0"

info:
  version: 1.0.0
  title: kubeRepo
  description: Manage Repos from k8s

schemes:
  - https
host: kubernetes.default.svc

paths:
  /apis/git.k8s.com/v1/repos:
    get:
      summary: Gets Repos
      description: Returns a list of repos
      responses:
        200:
          description: A list of repos
          schema:
            $ref: "#/definitions/repos"
      parameters:
        - name: watch
          uniqueItems: true
          type: boolean
          description: Watch for changes to the described resources and return them as a stream
            of add, update, and remove notifications. Specify resourceVersion.
          in: query
  /apis/git.k8s.com/v1/watch/repos:
    get:
      summary: Watch Repos
      description: Listen to events about repos
      responses:
        200:
          description: A stream of events
          schema:
            $ref: "#/definitions/event"
  /apis/git.k8s.com/v1/namespaces/{namespace}/repos/{name}:
    get:
      summary: Gets a specific Repo
      description: Returns a specific repo in a namespace
      parameters:
        - name: namespace
          in: path
          required: true
          description: The Repo's namespace
          type: string
        - name: name
          in: path
          required: true
          description: The Repo's name
          type: string
      responses:
        200:
          description: A single repo
          schema:
            $ref: "#/definitions/repo"
definitions:
  event:
    properties:
      type:
        type: string
      object:
        $ref: "#/definitions/repo"
  repos:
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/repo"
  repo:
    type: object
    properties:   
      branch:
        type: string
      image:
        type: string
      key:
        type: string
      oauth:
        type: string
      path:
        type: string
      repo:
        type: string
      then:
        type: string
      pvc:
        type: string
      metadata:
          $ref: "#/definitions/metadata"
  metadata:
    properties:
      name:
        type: string
      namespace:
        type: string
      selfLink:
        type: string